-- Phase 1.1b: two publications in one transaction must not tie.
--
-- published_at defaulted to now(), which is the transaction start time. Two runs
-- published in the same transaction therefore carried the SAME published_at, and
-- "the latest publication at or before a cutoff" became ambiguous: a cutoff just
-- before the second publication selected neither, and the tie-break fell through
-- to finished_at, which let a newer run answer for an earlier moment.
--
-- clock_timestamp() advances within a transaction, and an identity column gives
-- publication order a total, monotonic tie-break that does not depend on the
-- clock at all.

alter table pipeline.run_publications
  alter column published_at set default clock_timestamp();

alter table pipeline.run_publications
  add column if not exists publication_seq bigint generated by default as identity;

comment on column pipeline.run_publications.published_at is
  'Knowledge time of the publication decision. clock_timestamp(), not now(): two publications in one transaction are distinct events.';
comment on column pipeline.run_publications.publication_seq is
  'Total order of publications, used to break a published_at tie deterministically.';

create or replace function universe.authoritative_run_at(
  p_market_code ref.market_code,
  p_universe_version text,
  p_knowledge_cutoff timestamptz default now()
)
returns uuid
language sql
stable
set search_path = ''
as $$
  select p.run_id
  from pipeline.run_publications p
  join pipeline.runs r on r.run_id = p.run_id
  where r.market_code = p_market_code
    and r.versions ->> 'universe_version' = p_universe_version
    and p.published_at <= p_knowledge_cutoff
  order by p.published_at desc, p.publication_seq desc
  limit 1;
$$;

comment on function universe.authoritative_run_at(ref.market_code, text, timestamptz) is
  'The run that was authoritative at a knowledge cutoff: the latest publication at or before it, ordered by publication time and then by publication sequence. A run published later never answers for an earlier moment.';

grant execute on function universe.authoritative_run_at(ref.market_code, text, timestamptz)
  to surge_worker_prod, surge_worker_research, surge_readonly;
